import heroImage from "@/assets/velora-hero.jpg";
import aurelImage from "@/assets/aurel-terra.jpg";
import velaImage from "@/assets/vela-mini.jpg";
import solenImage from "@/assets/solen-gt.jpg";

export type Vehicle = { id:string; name:string; type:string; fuel:string; seats:number; transmission:string; location:string; price:number; range:number; ecoScore:number; match:number; image:string; tint:"mint"|"peach"|"lavender"; description:string; features:string[]; specs:{label:string;value:string}[]; reviews:{name:string;quote:string;rating:number}[] };
export const hero = heroImage;
export const fleet: Vehicle[] = [
 { id:"aurel-terra", name:"Aurel Terra", type:"SUV", fuel:"EV", seats:5, transmission:"Automatic", location:"Bandra West, Mumbai", price:4200, range:520, ecoScore:9.6, match:96, image:aurelImage, tint:"lavender", description:"A quiet, spacious electric SUV for long weekends, airport runs, and everything between.", features:["Panoramic glass roof","360° camera","Fast charging","Wireless CarPlay","Adaptive cruise"], specs:[{label:"Range",value:"520 km"},{label:"Power",value:"310 hp"},{label:"Boot",value:"480 L"},{label:"0–100",value:"5.8 sec"}], reviews:[{name:"Ananya R.",quote:"The calmest road trip we have ever taken. The car arrived spotless and fully charged.",rating:5},{name:"Mihir S.",quote:"Beautiful inside, easy to drive, and the handover took less than five minutes.",rating:5}] },
 { id:"vela-mini", name:"Vela Mini", type:"Hatchback", fuel:"EV", seats:4, transmission:"Automatic", location:"Indiranagar, Bengaluru", price:2600, range:340, ecoScore:9.4, match:91, image:velaImage, tint:"peach", description:"A bright city companion with a tiny turning circle, easy parking, and a surprisingly airy cabin.", features:["City assist","Fast charging","Wireless CarPlay","Keyless entry","Rear sensors"], specs:[{label:"Range",value:"340 km"},{label:"Power",value:"160 hp"},{label:"Boot",value:"280 L"},{label:"0–100",value:"7.4 sec"}], reviews:[{name:"Priya K.",quote:"Perfect for Bengaluru. It is tiny outside and feels generous inside.",rating:5}] },
 { id:"solen-gt", name:"Solen GT", type:"Sedan", fuel:"EV", seats:5, transmission:"Automatic", location:"Koregaon Park, Pune", price:6900, range:610, ecoScore:9.8, match:94, image:solenImage, tint:"mint", description:"A grand touring EV with a whisper-quiet cabin and enough range to make the long way home irresistible.", features:["Executive rear seats","Bowers audio","Air suspension","Level 2 autonomy","Massage seats"], specs:[{label:"Range",value:"610 km"},{label:"Power",value:"470 hp"},{label:"Boot",value:"510 L"},{label:"0–100",value:"4.1 sec"}], reviews:[{name:"Rohan M.",quote:"It feels like a lounge that happens to move very quickly.",rating:5}] },
];
export const locations = [{city:"Mumbai",place:"Bandra West Studio",detail:"24 vehicles · staffed 06:00–23:00"},{city:"Bengaluru",place:"Indiranagar Atelier",detail:"18 vehicles · doorstep delivery"},{city:"Pune",place:"Koregaon Park Hub",detail:"12 vehicles · fast charging"},{city:"Delhi NCR",place:"Aerocity Lounge",detail:"31 vehicles · airport handover"}];
export const formatPrice = (price:number) => `₹${price.toLocaleString("en-IN")}`;
